# Generated by Django 5.2.7 on 2025-10-16 05:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Kloud Technologies Ltd', max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, default='KTL', help_text='Unique organization code (e.g., KTL, DHKRES01)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Organization code must contain only uppercase letters, numbers, underscores, and hyphens', regex='^[A-Z0-9_-]+$')])),
                ('org_type', models.CharField(choices=[('isp', 'Internet Service Provider'), ('corporate', 'Corporate/Enterprise'), ('other', 'Other')], default='isp', max_length=20)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('trade_license', models.CharField(blank=True, max_length=100, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_img', models.ImageField(blank=True, help_text='Main organization logo', null=True, upload_to='organization_logos/')),
                ('dark_logo_img', models.ImageField(blank=True, help_text='Dark theme logo', null=True, upload_to='organization_logos/')),
                ('lite_logo_img', models.ImageField(blank=True, help_text='Light theme logo', null=True, upload_to='organization_logos/')),
                ('banner_img', models.ImageField(blank=True, help_text='Banner image for portal', null=True, upload_to='organization_banners/')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social sharing', null=True, upload_to='organization_og_images/')),
                ('favicon', models.ImageField(blank=True, help_text='Website favicon', null=True, upload_to='organization_favicons/')),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('currency_symbol', models.CharField(default='৳', max_length=5)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('revenue_sharing_enabled', models.BooleanField(default=True)),
                ('default_reseller_share', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('default_sub_reseller_share', models.DecimalField(decimal_places=2, default=45.0, max_digits=5)),
                ('default_ktl_share_with_sub', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('default_reseller_share_with_sub', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('api_version', models.CharField(default='v1.0', help_text='Dynamic API version for this organization', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='organizatio_code_c5d604_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_bdc355_idx'), models.Index(fields=['org_type'], name='organizatio_org_typ_b2fc82_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_manual_grace_days', models.IntegerField(default=9, help_text='Maximum manual grace days allowed')),
                ('disable_expiry', models.BooleanField(default=False, help_text='Disable automatic account expiry')),
                ('default_grace_days', models.IntegerField(default=1, help_text='Default grace period in days')),
                ('jump_billing', models.BooleanField(default=True, help_text='Enable jump billing for overdue accounts')),
                ('default_grace_hours', models.IntegerField(default=14, help_text='Default grace period in hours for hourly plans')),
                ('max_inactive_days', models.IntegerField(default=3, help_text='Maximum inactive days before account is disabled')),
                ('delete_permanent_disable_secret_from_mikrotik', models.IntegerField(default=1, help_text='Days before permanent disable is triggered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Billing Setting',
                'verbose_name_plural': 'Billing Settings',
                'db_table': 'billing_settings',
            },
        ),
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_area_to_mikrotik', models.BooleanField(default=False, help_text='Sync area information to MikroTik')),
                ('sync_address_to_mikrotik', models.BooleanField(default=False, help_text='Sync customer address to MikroTik')),
                ('sync_customer_mobile_to_mikrotik', models.BooleanField(default=False, help_text='Sync customer mobile number to MikroTik')),
                ('last_sync_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sync_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Sync Setting',
                'verbose_name_plural': 'Sync Settings',
                'db_table': 'sync_settings',
            },
        ),
    ]
