# Generated by Django 5.2.7 on 2025-10-15 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('organization_id', models.UUIDField(db_index=True, help_text='Organization UUID from Organization Service')),
                ('role_level', models.PositiveIntegerField(default=10, help_text='Lower = higher authority (1=SuperAdmin, 2=Admin, etc.)')),
                ('is_system_role', models.BooleanField(default=False, help_text='System-defined role, cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('can_assign_roles', models.BooleanField(default=False)),
                ('max_assignments', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'indexes': [models.Index(fields=['organization_id', 'is_active'], name='roles_organiz_1c97c0_idx'), models.Index(fields=['role_level'], name='roles_role_le_bf1a7a_idx'), models.Index(fields=['name'], name='roles_name_a96913_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_by_id', models.UUIDField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment_reason', models.TextField(blank=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('revoked_by_id', models.UUIDField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='roles.role')),
            ],
            options={
                'db_table': 'role_assignments',
            },
        ),
    ]
